### ISSUE TITLE
Set up code coverage and code quality mechanism

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticImageCaption#4]
The readme already makes a reference. :)

```
[![Build Status](https://travis-ci.org/SemanticMediaWiki/SemanticImageCaption.svg?branch=master)](https://travis-ci.org/SemanticMediaWiki/SemanticImageCaption)
[![Code Coverage](https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticImageCaption/badges/coverage.png?s=c5563fd91abeb49b37a6ef999198530b6796dd3c)](https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticImageCaption/)
[![Scrutinizer Quality Score](https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticImageCaption/badges/quality-score.png?s=9cc8ce493f63f5c2c22db71b2061b4b8c21f43ba)](https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticImageCaption/)
```

**Comment by kghbln** [comment]
@mwjames It will be really cool if you could to the travis and scrutinizer stuff

**Comment by mwjames** [comment]
> @mwjames It will be really cool if you could to the travis and scrutinizer stuff

- https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticImageCaption/
- https://travis-ci.org/github/SemanticMediaWiki/SemanticImageCaption/builds/682678817

For now Scrutinizer complains because there is no SMW 3.2 tag but SIC needs SMW 3.2 or master.

```
  - The requested package mediawiki/semantic-media-wiki >=3.2 is satisfiable by mediawiki/semantic-media-wiki[dev-master, 3.2.x-dev] but these conflict with your requirements or minimum-stability.
```

**Comment by kghbln** [comment]
Cool, many thanks. Hopefully we get SMW 3.2 off the ground soon!

**Comment by kghbln** [comment]
@mwjames I guess this is done. Scrutinizer is done too given the reason for the failiure.
